steps:
  # 1. Build and Tag
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'me-west1-docker.pkg.dev/$PROJECT_ID/osrm-israel/safe-route-solver:v1', '.']

# 2. Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'me-west1-docker.pkg.dev/$PROJECT_ID/osrm-israel/safe-route-solver:v1']

  # 3. Deploy with 2GiB RAM
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'safe-route-solver'
      - '--image'
      - 'me-west1-docker.pkg.dev/$PROJECT_ID/osrm-israel/safe-route-solver:v1'
      - '--region'
      - 'me-west1'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '1'
      - '--cpu-boost'
      - '--timeout'
      - '300'
      - '--allow-unauthenticated'